Add first edu edition elements
gomint/gomint pull request #356
Opened 2018-10-01 11:29 UTC by Kaooot

2018-10-02 14:49 UTC, Janmm14 requested changes

2018-10-02 14:49 UTC, Janmm14 commented on gomint-api/src/main/java/io/gomint/world/block/BlockBeryllium.java
> +public interface BlockBeryllium extends Block {
extends api BlockElement, same for other blocks in api

2018-10-03 18:17 UTC, geNAZt commented
Elements have multiple neutron values. The PR in its current state does not reflect that data.

2018-10-03 20:12 UTC, Janmm14 commented
Weight is dependant on neutrons. How should that be handled?

2018-10-04 08:04 UTC, Kaooot commented
Only the element Fluorine has two values given on the atomic weight. I think, I will use a int[] for the atomic weight as return.

2018-10-04 08:27 UTC, geNAZt requested changes
In general how does MC:PE handle the different neutron settings in Items/Blocks? There needs to be a way that this data isstored somewhere?

2018-10-04 08:27 UTC, geNAZt commented on gomint-api/src/main/java/io/gomint/world/block/BlockElement.java
> +    int[] getNeutrons();
Please add a documentation why a element has multiple neutron values and what todo with it

2018-10-26 14:09 UTC, lukeeey commented
Is this still be worked on @Kaooot ?

2018-10-26 18:02 UTC, Kaooot commented
nope you can close this pr if you want

2018-10-26 21:47 UTC, closed without merging

2018-10-27 02:22 UTC, XDqrkneZ commented
Why am I reading science words here