Add normal potions
gomint/gomint pull request #481
Opened 2018-12-25 17:37 UTC by Kaooot

2018-12-25 17:42 UTC, ghost requested changes
In general, please comment the case statements what potion that is and of what level

2018-12-25 17:42 UTC, Shad0wCore commented on gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPotion.java
> +import io.gomint.GoMint;
Add a blank line between the `package` and the `import` statement

2018-12-25 17:42 UTC, Shad0wCore commented on gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPotion.java
> +            case 0: case 1: case 2: case 3: case 4:
Do not inline `case` statements. (For each `case` statement a new line)

2018-12-25 18:26 UTC, Janmm14 commented on gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPotion.java
> +                // This potions do not have any effects
```suggestion
                // These potions do not have any effects
```

2018-12-25 18:28 UTC, Janmm14 commented on gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPotion.java
> +                player.setHealth( player.getHealth() <= player.getMaxHealth() - 2 ? 0 : player.getHealth() + 2 );
You don't need to check current health. Its done in setHealth already.

~~Also why you don't use an event for these potions?~~

2018-12-25 18:29 UTC, ghost submitted a review, later dismissed

2018-12-26 13:48 UTC, geNAZt requested changes

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +    @Parameter( name = "target", validator = TargetValidator.class )
This parameter should be optional = true

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +public class KillCommand extends Command {
Command is missing a permission

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +            target.setHealth( 0 );
Target should be damaged using #attack(float, DamageSource)

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +            }
Add a non player hint, something like "Please provider a player to kill: /kill [target]"

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +            commandOutput.success( "Killed " + target.getName() );
Maybe add a log output for who killed who (for audits)

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +                if ( player.getGamemode() != Gamemode.CREATIVE ) {
This is inconsistent behaviour since the target (if given) does not check for gamemodes

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +                    player.setHealth( 0 );
Same as above (#attack)

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +                    GoMint.instance().getPlayers().forEach( players -> players.sendMessage( player.getName() + " died" ) );
Same as above (logging for audit)

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/entity/EntityLiving.java
> +        if( amount <= 0 ) {
Spacing

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPotion.java
> +            case 0:
Please use either a enum or private constants with speaking names of the potion.

2018-12-26 13:48 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPotion.java
> +                EntityDamageEvent event = new EntityDamageEvent( player, EntityDamageEvent.DamageSource.HARM_EFFECT, 2 );
For case 23 + 24 please use #attack(float,DamagSource)

2018-12-26 17:21 UTC, Janmm14 requested changes

2018-12-26 17:21 UTC, Janmm14 commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +            System.out.println( commandSender instanceof PlayerCommandSender ? "" : ((EntityPlayer) commandSender).getName() + " was killed by " + target.getName() );
This inline if is wrong.

2018-12-26 17:21 UTC, Janmm14 commented on gomint-server/src/main/java/io/gomint/server/command/vanilla/KillCommand.java
> +            commandOutput.fail( "Please provide a player to kill: /kill [target]" );
Missing condition for the hint.

2019-01-01 16:09 UTC, closed without merging