Added the ability to send action bars
gomint/gomint pull request #81
Opened 2017-12-30 02:02 UTC by KCodeYT

2018-05-31 03:49 UTC, XDqrkneZ commented
merge?

2018-08-22 19:56 UTC, Janmm14 commented on gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
> +        this.sendActionbar( message, 1, 1, (long) 0.5, TimeUnit.SECONDS );
wtf why is here 0.5 casted to a long that looks senseless (also for the title

2018-08-22 20:33 UTC, geNAZt requested changes

2018-08-22 20:33 UTC, geNAZt commented on gomint-api/src/main/java/io/gomint/entity/EntityPlayer.java
> +    void sendActionbar(String message);
Please add javadoc

2018-08-22 20:33 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
> +        titlePacket.setFadeInTime( (int) unit.toMillis( fadein ) / 50 );
Cast the result to an int not the first operator

2018-08-22 20:33 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
> +        titlePacket.setStayTime( (int) unit.toMillis( duration ) / 50 );
Cast the result to an int not the first operator

2018-08-22 20:33 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
> +        titlePacket.setFadeOutTime( (int) unit.toMillis( fadeout ) / 50 );
Cast the result to an int not the first operator

2018-08-22 20:33 UTC, geNAZt commented on gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
> +        this.sendActionbar( message, 1, 1, (long) 0.5, TimeUnit.SECONDS );
Please use a more proper unit (Milliseconds) to avoid casting

2018-08-22 20:36 UTC, lukeeey commented
I did this in my commands PR too

2018-08-22 20:38 UTC, geNAZt commented
Oh then that has been slipped through, will look into that now

2018-08-22 20:42 UTC, lukeeey commented
@geNAZt Nevermind, i was wrong.

2018-10-03 18:33 UTC, closed without merging